### PR TITLE
Disable window-divider when deactive.

### PR DESCRIPTION
**Pull request by jcs090218**
as title

### CODE REVIEW

**Comment by jcs090218** [comment]
@tautologyclub What do you think about this patch? I think this is reasonable right?

**Comment by kevinboulain** [comment]
Wouldn't it be best to remember previous values like we do for `(setq mode-line-format feebleline--mode-line-format-previous)`? Otherwise I don't really see the point of 'restoring' when disabling the mode.

**Comment by jcs090218** [comment]
> Wouldn't it be best to remember previous values like we do for `(setq mode-line-format feebleline--mode-line-format-previous)`? Otherwise I don't really see the point of 'restoring' when disabling the mode.

@ether42  Fixed!

**Comment by jcs090218** [comment]
@tautologyclub @endian-benjamin Ping.

**Pull request merged**
